spring.application.name=transaction-service
server.port=8082

#POSTGRESS DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/novabank_transaction_service_db
spring.datasource.username=postgres
spring.datasource.password=root

#JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update